from selenium.webdriver.common.by import By


class AccountCreation:

    reg_email_input = (By.XPATH, "//input[@name='email']")
    register_button = (By.XPATH, "//button[@type='submit']")
    accept_term_checkbox = (By.XPATH, "//input[@name='acceptTerms']")
    terms_link = (By.CLASS_NAME, "css-1a9gzt0")
    sing_in_link = (By.XPATH, "//a[@href='/devs']")
    forgot_password_link = (By.XPATH, "//a[@href='/devs/reset-password']")
    message_email_required = (By.XPATH, "//p[contains(@class,'Mui-error')]//span")
    register_link_assert = (By.PARTIAL_LINK_TEXT, "Register")
    message_get_started = (By.TAG_NAME, "h1")
    message_already_have_account = (By.TAG_NAME, "h6")
    message_valid_email = (By.XPATH, "//p[contains(@class,'MuiFormHelperText-filled')]//span")
    message_terms_clients = (By.TAG_NAME, "h6")
    sing_in_link_assert = (By.PARTIAL_LINK_TEXT, "Sign in")
    message_reset_password = (By.XPATH, "//button[@type='submit']//span")
    register_fb_button = (By.XPATH, "//a[@href='/developers/auth/facebook']")
    message_fb = (By.CLASS_NAME, "login_page")
    fb_password_input = (By.XPATH, "//input[@name ='pass']")
    log_in_fb_button = (By.ID, "loginbutton")
    accept_fb_button = (By.XPATH, "//button[@data-cookiebanner='accept_button']")
    register_google_button = (By.XPATH, "//a[@href='/developers/auth/google']")
    google_email_input = (By.XPATH, "//input[@type='email']")
    google_next_button = (By.XPATH, "//button[@type='button']")
    message_google = (By.XPATH, "//div[@jsname='YASyvd']")
    register_github_button = (By.XPATH, "//a[@href='/developers/auth/github']")
    github_email_input = (By.XPATH, "//input[@name='login']")
    github_password_input = (By.XPATH, "//input[@name='password']")
    github_sing_in_button = (By.XPATH, "//input[@type='submit']")
    message_github = (By.XPATH, "//h2[contains(@class,'mb-4')]")
    register_linkedin_button = (By.XPATH, "//a[@href='/developers/auth/linkedin']")
    linkedin_email_input = (By.ID, "username")
    linkedin_password_input = (By.ID, "password")
    linkedin_sing_in_button = (By.XPATH, "//button[@type='submit']")
    message_linkedin = (By.XPATH, "//h1[@class='header__logo']")


class LoginLocators:

    log_email_input = (By.XPATH, "//input[@name='email']")
    password_input = (By.XPATH, "//INPUT[@name='password']")
    sing_in_button = (By.XPATH, "//button[@type='submit']")
    reset_password_button = (By.XPATH, "//button[@type='submit']")
    message_my_profile = (By.XPATH, "//div[@class='css-jtlf28']")
    message_reset_password_assert = (By.TAG_NAME, "h1")
    message_password_assert = (By.XPATH, "//div[contains(@class,'MuiGrid-align-items-xs-center')]//label")
    register_button = (By.XPATH, "//a[@href='/devs/signup']")


class SearchLocators:

    search_home_input = (By.XPATH, "//input[@placeholder='Search']")
    search_js_category_span = (By.XPATH, "//span[text()='JavaScript']")
    message_results_search_assert = (By.XPATH, "//span[@class='css-lp92kk']")
    is_chat_visibility_assert = (By.XPATH, "//div[@id='chat-widget-container']")
    message_error_search = (By.XPATH, "//span[@class='css-x62lqu']")
    search_js_category_xpath = (By.XPATH, "//span[text()='JavaScript']")
    search_html_category_xpath = (By.XPATH, "//span[text()='HTML']")
    search_category_xpath = (By.XPATH, "//span[@class='css-g90fw7']")
#    back_search_button = (By.XPATH, "//button[contains(@class,'css-lp92kk')]//span")


class ButtonLocators:

    long_menu_button = (By.XPATH, "//button[contains(@class,'css-5cj5tj')]")
    js_button = (By.XPATH, "//a[@href='/all/javascript']")
    is_js_visibility_assert = (By.XPATH, "//img[@src='/static/media/javascript.59ed3183.svg']")
    html_button = (By.XPATH, "//div[contains(@class,'css-15zzcp6')]")
    is_html_visibility_assert = (By.XPATH, "//img[@src='/static/media/html.d0655391.svg']")
    php_button = (By.XPATH, "//div[contains(@class,'css-8gwc1d')]")
    is_php_visibility_assert = (By.XPATH, "//img[@src='/static/media/php.c114d6f0.svg']")
    ruby_button = (By.XPATH, "//div[contains(@class,'css-1tfd2n2')]")
    is_ruby_visibility_assert = (By.XPATH, "//img[@src='/static/media/ruby.b06393ff.svg']")
    python_button = (By.XPATH, "//div[contains(@class,'css-1cj734a')]")
    is_python_visibility_assert = (By.XPATH, "//img[@src='/static/media/python.4346b5b4.svg']")
    java_button = (By.XPATH, "//div[contains(@class,'css-1a8qs4i')]")
    is_java_visibility_assert = (By.XPATH, "//img[@src='/static/media/java.71df257a.svg']")
    net_button = (By.XPATH, "//div[contains(@class,'css-1a8qs4i')]")
    is_net_visibility_assert = (By.XPATH, "//img[@src='/static/media/java.71df257a.svg']")
    scala_button = (By.XPATH, "//div[contains(@class,'css-g42t18')]")
    is_scala_visibility_assert = (By.XPATH, "//img[@src='/static/media/scala.00f4a72c.svg']")
    c_button = (By.XPATH, "//div[contains(@class,'css-1keyhgs')]")
    is_c_visibility_assert = (By.XPATH, "//img[@src='/static/media/c.069f44ae.svg']")
    mobile_button = (By.XPATH, "//div[contains(@class,'css-4ommue')]")
    is_mobile_visibility_assert = (By.XPATH, "//img[@src='/static/media/mobile.865f38ae.svg']")
    testing_button = (By.XPATH, "//div[contains(@class,'css-1ihgbwn')]")
    is_testing_visibility_assert = (By.XPATH, "//img[@src='/static/media/testing.4e552286.svg']")
    devops_button = (By.XPATH, "//div[contains(@class,'css-s0yxfw')]")
    is_devops_visibility_assert = (By.XPATH, "//img[@src='/static/media/devops.3b10a632.svg']")
    admin_button = (By.XPATH, "//div[contains(@class,'css-4n2y9')]")
    is_admin_visibility_assert = (By.XPATH, "//img[@src='/static/media/admin.0e6e6e83.svg']")
    ux_ui_button = (By.XPATH, "//div[contains(@class,'css-17oesie')]")
    is_ux_ui_visibility_assert = (By.XPATH, "//img[@src='/static/media/ux.94ff0a9f.svg']")
    pm_button = (By.XPATH, "//div[contains(@class,'css-1tq2vdb')]")
    is_pm_visibility_assert = (By.XPATH, "//img[@src='/static/media/pm.ad96b893.svg']")
    game_button = (By.XPATH, "//div[contains(@class,'css-1lzwc3z')]")
    is_game_visibility_assert = (By.XPATH, "//img[@src='/static/media/game.6b4b59e5.svg']")
    analytics_button = (By.XPATH, "//div[contains(@class,'css-v9n6oo')]")
    is_analytics_visibility_assert = (By.XPATH, "//img[@src='/static/media/analytics.49df0e86.svg']")
    security_button = (By.XPATH, "//div[contains(@class,'css-1jtyjfq')]")
    is_security_visibility_assert = (By.XPATH, "//img[@src='/static/media/security.df7faefd.svg']")
    data_button = (By.XPATH, "//div[contains(@class,'css-16qtfkr')]")
    is_data_visibility_assert = (By.XPATH, "//img[@src='/static/media/data.b2867c21.svg']")
    go_button = (By.XPATH, "//div[contains(@class,'css-19p1r5')]")
    is_go_visibility_assert = (By.XPATH, "//img[@src='/static/media/go.ac5a94e5.svg']")
    support_button = (By.XPATH, "//div[contains(@class,'css-16bptvm')]")
    is_support_visibility_assert = (By.XPATH, "//img[@src='/static/media/support.0c44fab2.svg']")
    erp_button = (By.XPATH, "//div[contains(@class,'css-5z85mt')]")
    is_erp_visibility_assert = (By.XPATH, "//img[@src='/static/media/erp.37176ebb.svg']")
    architecture_button = (By.XPATH, "//div[contains(@class,'css-1b8ndnf')]")
    is_architecture_visibility_assert = (By.XPATH, "//img[@src='/static/media/architecture.595da3c5.svg']")
    other_button = (By.XPATH, "//div[contains(@class,'css-zmxgek')]")
    is_other_visibility_assert = (By.XPATH, "//img[@src='/static/media/other.c34be08c.svg']")


class CitySelectionLocators:

    locations_button = (By.XPATH, "//button[contains(@class,'css-rbgze')]")
    city_warsaw_button = (By.XPATH, "//a[@href='/warszawa']")
    message_results_city_selected_assert = (By.XPATH, "//span[@class='MuiButton-label']")
    city_krakow_button = (By.XPATH, "//a[@href='/krakow']")
    city_wroclaw_button = (By.XPATH, "//a[@href='/wroclaw']")
    city_poznan_button = (By.XPATH, "//a[@href='/poznan']")
    city_trojmiasto_button = (By.XPATH, "//a[@href='/trojmiasto']")
    city_slask_button = (By.XPATH, "//a[@href='/slask']")
    city_new_york_button = (By.XPATH, "//a[@href='/new-york']")
    city_sydney_button = (By.XPATH, "//a[@href='/sydney']")
    city_berlin_button = (By.XPATH, "//a[@href='/berlin']")
    city_san_francisco_button = (By.XPATH, "//a[@href='/san-francisco']")
    city_london_button = (By.XPATH, "//a[@href='/london']")
    other_locations_button = (By.XPATH, "//button[@class='css-tdkxar']")
    city_bialystok_button = (By.XPATH, "//a[@href='/bialystok']")
    city_biesko_biala_button = (By.XPATH, "//a[@href='/bielsko-biala']")
    city_bydgoszcz_button = (By.XPATH, "//a[@href='/bydgoszcz']")
    city_czestochowa_button = (By.XPATH, "//a[@href='/czestochowa']")
    city_kielce_button = (By.XPATH, "//a[@href='/kielce']")
    city_lublin_button = (By.XPATH, "//a[@href='/lublin']")
    city_lodz_button = (By.XPATH, "//a[@href='/lodz']")
    city_olsztyn_button = (By.XPATH, "//a[@href='/olsztyn']")
    city_opole_button = (By.XPATH, "//a[@href='/opole']")
    city_rzeszow_button = (By.XPATH, "//a[@href='/rzeszow']")
    city_szczecin_button = (By.XPATH, "//a[@href='/szczecin']")
    city_torun_button = (By.XPATH, "//a[@href='/torun']")
    city_zielona_gora_button = (By.XPATH, "//a[@href='/zielona_gora']")
    clear_filter_button = (By.XPATH, "//a[contains(@class,'css-1avvcn0')]")
    another_click_locations_button = (By.XPATH, "//button[contains(@class,'css-1atb8pb')]")
    message_offers_assert = (By.XPATH, "//div[@class='css-7grlje']")


class MoreFiltersLocators:

    more_filters_button = (By.XPATH, "//button[contains(@class,'css-p1hmmo')]")
    b2b_button = (By.XPATH, "//span[text()='B2B']")
    show_offers_button = (By.XPATH, "//span[text()='Show offers']")
    message_search_b2b_assert = (By.XPATH, "//a[@href='/?employmentType=b2b']")
    permanent_button = (By.XPATH, "//span[text()='Permanent']")
    message_search_permanent_assert = (By.XPATH, "//a[@href='/?employmentType=permanent']")
    mandate_contract_button = (By.XPATH, "//span[text()='Mandate Contract']")
    message_search_mandate_contract_assert = (By.XPATH, "//a[@href='/?employmentType=mandate_contract']")
    all_button = (By.XPATH, "//button[contains(@class,'css-2ocjl7')]")
    another_click_locations_button = (By.XPATH, "//button[contains(@class,'css-jonq2z')]")